{
 "title": "Playground",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Mac Mini Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"server:9100\"}-node_memory_MemAvailable_bytes",
     "legendFormat": "Memory"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"server:9100\"}-node_memory_SwapFree_bytes",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Mac Mini fan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{instance=\"server:9100\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Mac Mini CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\",instance=\"server:9100\",cpu=~\"0|1|2|3\"}[1m]))",
     "legendFormat": "E cores"
    },
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\",instance=\"server:9100\",cpu=~\"4|5|6|7\"}[1m]))",
     "legendFormat": "P cores"
    }
   ]
  },
  {
   "title": "Mac Mini power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "node_hwmon_power_watt{instance=\"server:9100\"} * on (instance, chip, sensor) group_left (label) node_hwmon_sensor_label",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Mac Mini temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"server:9100\"} * on (instance, chip, sensor) group_left (label) node_hwmon_sensor_label",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}