{
 "title": "sshesame",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "geomap",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"ssheame\"} | json | event_type = `connection`"
    },
    {
     "expr": "{job=\"ssheame\"} | json | event_type = `session`"
    },
    {
     "expr": "{job=\"ssheame\"} | json | event_type = `direct_tcpip`"
    }
   ]
  },
  {
   "title": "Connection rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(sshesame_ssh_connections_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sshesame_active_ssh_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session channel rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(sshesame_session_channels_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active session channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sshesame_active_session_channels",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP/IP channel rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(sshesame_tcpip_channels_total[1h])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Active TCP/IP channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "sshesame_active_tcpip_channels", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Client versions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"ssheame\"} | json | event_type = `connection` [$__auto])) by (event_client_version)",
     "legendFormat": "{{event_client_version}}"
    }
   ]
  },
  {
   "title": "Usernames",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"ssheame\"} | json | event_type = `password_auth` [$__auto])) by (event_user)",
     "legendFormat": "{{event_user}}"
    }
   ]
  },
  {
   "title": "Exec requests",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{job=\"ssheame\"} | json | event_type = `exec` | line_format `{{.event_command}}`"
    }
   ]
  },
  {
   "title": "Session channel input",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "{job=\"ssheame\"} | json | event_type = `session_input` | line_format `{{.event_input}}`"
    }
   ]
  }
 ]
}